services:
  db:
    image: postgres:16
    container_name: swim_pg
    environment:
      POSTGRES_DB: swim
      POSTGRES_USER: swim_user
      POSTGRES_PASSWORD: swim_pass

    ports:
      - "15432:5432"
    volumes:
      - swim_pg_data:/var/lib/postgresql/data

volumes:
  swim_pg_data:
